let state={xp:0,credits:250,level:1,name:'Explorer',avatar:'AI Explorer',world:0,mission:0,selected:null};
const worlds=[
{name:'ALGO LABS',icon:'🟢',missions:[['Awaken the AI','What is the primary role of a Large Language Model?',['Store electricity','Generate and understand language','Replace databases','Compile hardware'],1],['AI Foundations','Which technology is commonly used to retrieve relevant documents for RAG?',['Vector embeddings','CSS','JPEG compression','SMTP'],0]]},
{name:'PYTHON VALLEY',icon:'🐍',missions:[['Debug the Code','Which keyword returns a value from a Python function?',['yield','return','send','output'],1],['Data Quest','Which structure stores key-value pairs?',['List','Tuple','Dictionary','Set'],2]]},
{name:'GENAI LAB',icon:'🧠',missions:[['Prompt Hacker','Which addition usually makes a prompt more precise?',['More emojis','Role + context + constraints','Less context','Random examples'],1],['LLM Core','What does a tokenizer primarily do?',['Turns text into tokens','Trains GPUs','Stores passwords','Runs SQL'],0]]},
{name:'RAG FORTRESS',icon:'🏰',missions:[['Repair the Pipeline','Choose the correct RAG flow.',['LLM → Docs → Embeddings → Retrieval','Docs → Chunks → Embeddings → Vector DB → Retrieval → LLM','CSS → API → LLM','Prompt → GPU → Browser'],1],['Ground Truth','What is a major benefit of retrieval grounding?',['Reduces unsupported answers','Makes GPUs faster','Removes all latency','Eliminates databases'],0]]},
{name:'AGENT CITY',icon:'🤖',missions:[['Tool Calling','An agent needs live weather. What should it use?',['A static prompt','A weather API/tool','More temperature','A CSS file'],1],['Agent Loop','What helps prevent an agent from looping forever?',['No tools','Iteration limits and stopping conditions','Higher temperature','More tokens only'],1]]}
];
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0)}
function pick(el,name){document.querySelectorAll('.avatar').forEach(a=>a.classList.remove('selected'));el.classList.add('selected');state.avatar=name}
function startGame(){state.name=document.getElementById('playerName').value.trim()||'Explorer';document.getElementById('welcome').textContent='Welcome, '+state.name;document.getElementById('leaderName').textContent=state.name.toUpperCase();show('map');toast('AI IDENTITY CREATED • +100 STARTER XP');addXP(100)}
function addXP(n){state.xp+=n;state.level=Math.floor(state.xp/500)+1;document.getElementById('xp').textContent=String(state.xp).padStart(4,'0');document.getElementById('level').textContent=String(state.level).padStart(2,'0');document.getElementById('leaderXP').textContent=state.xp+' XP'}
function openWorld(i){if(i===5){if(state.xp<800){toast('🔒 Reach 800 XP to unlock the AI Frontier');return}show('boss');return}state.world=i;state.mission=0;loadMission()}
function loadMission(){const w=worlds[state.world],m=w.missions[state.mission%w.missions.length];document.getElementById('missionWorld').textContent=w.name;document.getElementById('missionIcon').textContent=w.icon;document.getElementById('missionNo').textContent='MISSION '+String(state.mission+1).padStart(2,'0');document.getElementById('missionTitle').textContent=m[0];document.getElementById('missionText').textContent=m[1];document.getElementById('feedback').textContent='';document.getElementById('submitBtn').disabled=false;state.selected=null;document.getElementById('challenge').innerHTML=m[2].map((x,i)=>`<button class="choice" onclick="selectChoice(${i})">${String.fromCharCode(65+i)}. ${x}</button>`).join('');show('mission')}
function selectChoice(i){state.selected=i;document.querySelectorAll('.choice').forEach((b,n)=>b.classList.toggle('selected',n===i))}
function submitAnswer(){if(state.selected===null){toast('Choose an answer first');return}const m=worlds[state.world].missions[state.mission%2];if(state.selected===m[3]){addXP(100);state.credits+=50;document.getElementById('credits').textContent=state.credits;document.getElementById('feedback').innerHTML='✓ CORRECT — SYSTEM UNLOCKED';toast('+100 XP  •  +50 CREDITS');state.mission++;setTimeout(()=>loadMission(),800)}else{document.getElementById('feedback').innerHTML='✕ NOT QUITE. Re-read the challenge and try again.';toast('MISSION FAILED • TRY AGAIN')}}
function bossAnswer(ok){const f=document.getElementById('bossFeedback');if(ok){addXP(500);f.innerHTML='🏆 BOSS DEFEATED — Your response is grounded in retrieved evidence.';toast('+500 XP • AI ARCHITECT BADGE');setTimeout(()=>show('leaderboard'),1400)}else{f.innerHTML='⚠️ The system is still vulnerable. Choose the evidence-grounded strategy.'}}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2200)}
document.getElementById('playerName').addEventListener('keydown',e=>{if(e.key==='Enter')startGame()});
